global:
  scrape_interval: 5s

scrape_configs:
  - job_name: services
    static_configs:
      - targets: ["shop:8000"]
        labels: { service: shop }
      - targets: ["users:8000"]
        labels: { service: users }
      - targets: ["inventory:8000"]
        labels: { service: inventory }
      - targets: ["payments:8000"]
        labels: { service: payments }
